name: Build APP

on:
  # 开启手动触发按钮
  workflow_dispatch:
  push:
    branches: [ "master", "old-android" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 构建步骤
      - uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: .
          output-path: app-debug.apk
          fastlane-env: "debug"
          ruby-version: "3.3.0"

      # 修改点：去掉了 if: github.event_name == 'pull_request'
      # 这样无论你怎么触发，都会把生成的 APK 上传出来
      - uses: actions/upload-artifact@v3
        name: Upload app APK
        with:
          name: App-Debug-Version
          path: app-debug.apk
      
      #以此往下删除了所有关于 Sign (签名) 的步骤，因为 Fork 仓库没有密钥必挂
